import type { GlobeShowNode, SnippetResult } from "./types";

export const MOCK_SHOWS: GlobeShowNode[] = [
  {
    showId: "show_1",
    title: "Pitch Dark Product Stories",
    slug: "pitch-dark-product-stories",
    hostName: "Elena Vance",
    description: "Late-night tales of high-stakes product launches, edge-case bugs, and startup redemption arcs.",
    coverArtUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&h=400&fit=crop",
    isAmped: true,
    ampScore: 92,
    isClaimed: true,
    coordinates: { x: 0.12, y: 0.58, z: -0.25 },
  },
  {
    showId: "show_2",
    title: "Side Quest Signals",
    slug: "side-quest-signals",
    hostName: "Marcus Sterling",
    description: "Exploring unexpected hacker hobbies, synthesizer tinkering, and creative tangents that fuel great software.",
    coverArtUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
    isAmped: false,
    ampScore: 68,
    isClaimed: false,
    coordinates: { x: -0.45, y: -0.22, z: 0.35 },
  },
  {
    showId: "show_3",
    title: "The Synthetic Architect",
    slug: "the-synthetic-architect",
    hostName: "Dr. Maya Lin",
    description: "Deep conversations with neural systems designers, agentic framework engineers, and prompt craftsmen.",
    coverArtUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    isAmped: true,
    ampScore: 89,
    isClaimed: true,
    coordinates: { x: 0.38, y: -0.42, z: 0.52 },
  },
  {
    showId: "show_4",
    title: "Kernel Panic Confidential",
    slug: "kernel-panic-confidential",
    hostName: "Devon Reed",
    description: "Post-mortems from the world's most catastrophic distributed outages and heroic zero-day hotfixes.",
    coverArtUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=400&fit=crop",
    isAmped: true,
    ampScore: 78,
    isClaimed: false,
    coordinates: { x: -0.28, y: 0.62, z: 0.38 },
  },
  {
    showId: "show_5",
    title: "Prompt & Circumstance",
    slug: "prompt-and-circumstance",
    hostName: "Tara Chen",
    description: "Where literature, philosophy, and autonomous coding agents collide. Reflections on future cognition.",
    coverArtUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=400&fit=crop",
    isAmped: false,
    ampScore: 54,
    isClaimed: false,
    coordinates: { x: 0.52, y: 0.15, z: -0.58 },
  },
  {
    showId: "show_6",
    title: "Neon Latency Nights",
    slug: "neon-latency-nights",
    hostName: "Kaelen Voss",
    description: "A fast-paced audio odyssey through global fiber optics, undersea cables, and sub-millisecond trading rigs.",
    coverArtUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    isAmped: true,
    ampScore: 95,
    isClaimed: true,
    coordinates: { x: -0.62, y: -0.32, z: -0.28 },
  },
  {
    showId: "show_7",
    title: "Silicon Disco Radio",
    slug: "silicon-disco-radio",
    hostName: "Zara Fox",
    description: "Where 70s funk and high-frequency distributed computing merge into sonic groove sessions.",
    coverArtUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&h=400&fit=crop",
    isAmped: true,
    ampScore: 84,
    isClaimed: false,
    coordinates: { x: 0.25, y: -0.65, z: -0.32 },
  },
  {
    showId: "show_8",
    title: "Vector Space Odyssey",
    slug: "vector-space-odyssey",
    hostName: "Niko Thorne",
    description: "Navigating high-dimensional embeddings, semantic indexing, and the future of multimodal search.",
    coverArtUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&h=400&fit=crop",
    isAmped: true,
    ampScore: 91,
    isClaimed: true,
    coordinates: { x: -0.55, y: 0.35, z: -0.45 },
  },
];

export const MOCK_SNIPPETS: SnippetResult[] = [
  {
    snippetId: "snippet_1",
    showId: "show_1",
    episodeId: "episode_1",
    showTitle: "Pitch Dark Product Stories",
    episodeTitle: "The launch that nearly missed midnight",
    hookText: "How one onboarding checkbox almost tanked the whole product launch.",
    transcriptExcerpt:
      "We thought the hard part was done, then one single checkbox blocked all signups across three continents.",
    startTime: 615,
    endTime: 660,
    audioUrl: "https://actions.google.com/sounds/v1/ambiences/coffee_shop.ogg",
    coverArtUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&h=400&fit=crop",
    similarityScore: 0.95,
    ampScore: 92,
  },
  {
    snippetId: "snippet_2",
    showId: "show_3",
    episodeId: "episode_2",
    showTitle: "The Synthetic Architect",
    episodeTitle: "Neural memory loops and autonomous reflexes",
    hookText: "Why vector retrieval alone fails without recursive agent loops.",
    transcriptExcerpt:
      "If you only feed top-k chunks to your model, it cannot form persistent associative habits.",
    startTime: 420,
    endTime: 465,
    audioUrl: "https://actions.google.com/sounds/v1/ambiences/rain_heavy.ogg",
    coverArtUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    similarityScore: 0.88,
    ampScore: 89,
  },
  {
    snippetId: "snippet_3",
    showId: "show_6",
    episodeId: "episode_3",
    showTitle: "Neon Latency Nights",
    episodeTitle: "Subsea fiber and transoceanic light bursts",
    hookText: "Crossing the Atlantic Ocean in under sixty milliseconds.",
    transcriptExcerpt:
      "Every single nanosecond was engineered out of the glass. Glass purity at the bottom of the ocean.",
    startTime: 180,
    endTime: 225,
    audioUrl: "https://actions.google.com/sounds/v1/ambiences/coffee_shop.ogg",
    coverArtUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    similarityScore: 0.91,
    ampScore: 95,
  },
];
